import { Component } from '@angular/core';
import { DataService } from '../../data.service';
import { GithubRepoCardComponent } from './github-repo-card/github-repo-card.component';
import { GithubCalendarComponent } from '../github-calendar/github-calendar.component';
import { NgFor } from '@angular/common';

@Component({
  selector: 'app-projects',
  standalone: true,
  imports: [GithubRepoCardComponent, GithubCalendarComponent, NgFor],
  templateUrl: './projects.component.html',
  styleUrl: './projects.component.css'
})
export class ProjectsComponent {
  gitRepos: any;

  constructor(private appService: DataService) { }
  ngOnInit(): void {
    this.gitRepos=repoData;
    // this.appService.getAllGitReposData().subscribe((response: any) => {
    //   this.gitRepos = response;
    // }, (error: any) => {
    //   console.error('Error fetching Repos data:', error);
    // });
  }
}

const repoData:any = [
  {
    id: 670273621,
    node_id: 'R_kgDOJ_OQVQ',
    name: 'Dyan-up-v1-RestAPI',
    full_name: 'marotiuppe/Dyan-up-v1-RestAPI',
    private: false,
    owner: {
      login: 'marotiuppe',
      id: 61408288,
      node_id: 'MDQ6VXNlcjYxNDA4Mjg4',
      avatar_url: 'https://avatars.githubusercontent.com/u/61408288?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/marotiuppe',
      html_url: 'https://github.com/marotiuppe',
      followers_url: 'https://api.github.com/users/marotiuppe/followers',
      following_url: 'https://api.github.com/users/marotiuppe/following{/other_user}',
      gists_url: 'https://api.github.com/users/marotiuppe/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/marotiuppe/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/marotiuppe/subscriptions',
      organizations_url: 'https://api.github.com/users/marotiuppe/orgs',
      repos_url: 'https://api.github.com/users/marotiuppe/repos',
      events_url: 'https://api.github.com/users/marotiuppe/events{/privacy}',
      received_events_url: 'https://api.github.com/users/marotiuppe/received_events',
      type: 'User',
      site_admin: false
    },
    html_url: 'https://github.com/marotiuppe/Dyan-up-v1-RestAPI',
    description: "A comprehensive RestAPI's for managing students, including tracking their daily events, schedules, and other activities. It offers features for organizing and monitoring academic and extracurricular activities efficiently.",
    fork: false,
    url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI',
    forks_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/forks',
    keys_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/teams',
    hooks_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/hooks',
    issue_events_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/issues/events{/number}',
    events_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/events',
    assignees_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/assignees{/user}',
    branches_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/branches{/branch}',
    tags_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/tags',
    blobs_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/languages',
    stargazers_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/stargazers',
    contributors_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/contributors',
    subscribers_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/subscribers',
    subscription_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/subscription',
    commits_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/contents/{+path}',
    compare_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/merges',
    archive_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/downloads',
    issues_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/issues{/number}',
    pulls_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/labels{/name}',
    releases_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/releases{/id}',
    deployments_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-RestAPI/deployments',
    created_at: '2023-07-24T17:14:47Z',
    updated_at: '2024-07-27T10:52:23Z',
    pushed_at: '2023-08-11T17:04:31Z',
    git_url: 'git://github.com/marotiuppe/Dyan-up-v1-RestAPI.git',
    ssh_url: 'git@github.com:marotiuppe/Dyan-up-v1-RestAPI.git',
    clone_url: 'https://github.com/marotiuppe/Dyan-up-v1-RestAPI.git',
    svn_url: 'https://github.com/marotiuppe/Dyan-up-v1-RestAPI',
    homepage: 'https://dyan-up-v1-ui.vercel.app',
    size: 130,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Java',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: false,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: ['daily-tracking', 'dyan-up', 'monitoring', 'student'],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'main',
    languages: { Java: 238819 }
  }, {
    id: 677478751,
    node_id: 'R_kgDOKGGBXw',
    name: 'Dyan-up-v1-ui',
    full_name: 'marotiuppe/Dyan-up-v1-ui',
    private: false,
    owner: {
      login: 'marotiuppe',
      id: 61408288,
      node_id: 'MDQ6VXNlcjYxNDA4Mjg4',
      avatar_url: 'https://avatars.githubusercontent.com/u/61408288?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/marotiuppe',
      html_url: 'https://github.com/marotiuppe',
      followers_url: 'https://api.github.com/users/marotiuppe/followers',
      following_url: 'https://api.github.com/users/marotiuppe/following{/other_user}',
      gists_url: 'https://api.github.com/users/marotiuppe/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/marotiuppe/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/marotiuppe/subscriptions',
      organizations_url: 'https://api.github.com/users/marotiuppe/orgs',
      repos_url: 'https://api.github.com/users/marotiuppe/repos',
      events_url: 'https://api.github.com/users/marotiuppe/events{/privacy}',
      received_events_url: 'https://api.github.com/users/marotiuppe/received_events',
      type: 'User',
      site_admin: false
    },
    html_url: 'https://github.com/marotiuppe/Dyan-up-v1-ui',
    description: 'A comprehensive web application for managing students, including tracking their daily events, schedules, and other activities. It offers features for organizing and monitoring academic and extracurricular activities efficiently.',
    fork: false,
    url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui',
    forks_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/forks',
    keys_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/teams',
    hooks_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/hooks',
    issue_events_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/issues/events{/number}',
    events_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/events',
    assignees_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/assignees{/user}',
    branches_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/branches{/branch}',
    tags_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/tags',
    blobs_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/languages',
    stargazers_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/stargazers',
    contributors_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/contributors',
    subscribers_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/subscribers',
    subscription_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/subscription',
    commits_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/contents/{+path}',
    compare_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/merges',
    archive_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/downloads',
    issues_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/issues{/number}',
    pulls_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/labels{/name}',
    releases_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/releases{/id}',
    deployments_url: 'https://api.github.com/repos/marotiuppe/Dyan-up-v1-ui/deployments',
    created_at: '2023-08-11T17:12:26Z',
    updated_at: '2024-07-27T10:43:24Z',
    pushed_at: '2023-08-11T17:28:50Z',
    git_url: 'git://github.com/marotiuppe/Dyan-up-v1-ui.git',
    ssh_url: 'git@github.com:marotiuppe/Dyan-up-v1-ui.git',
    clone_url: 'https://github.com/marotiuppe/Dyan-up-v1-ui.git',
    svn_url: 'https://github.com/marotiuppe/Dyan-up-v1-ui',
    homepage: 'https://dyan-up-v1-ui.vercel.app',
    size: 12292,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'HTML',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: ['angular', 'dyan-ui', 'dyan-up-ui', 'student', 'ui'],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'main',
    languages: { TypeScript: 23539, CSS: 17097, HTML: 6913 }
  },
  {
    id: 833745020,
    node_id: 'R_kgDOMbHwfA',
    name: 'my-portfolio',
    full_name: 'marotiuppe/my-portfolio',
    private: false,
    owner: {
      login: 'marotiuppe',
      id: 61408288,
      node_id: 'MDQ6VXNlcjYxNDA4Mjg4',
      avatar_url: 'https://avatars.githubusercontent.com/u/61408288?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/marotiuppe',
      html_url: 'https://github.com/marotiuppe',
      followers_url: 'https://api.github.com/users/marotiuppe/followers',
      following_url: 'https://api.github.com/users/marotiuppe/following{/other_user}',
      gists_url: 'https://api.github.com/users/marotiuppe/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/marotiuppe/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/marotiuppe/subscriptions',
      organizations_url: 'https://api.github.com/users/marotiuppe/orgs',
      repos_url: 'https://api.github.com/users/marotiuppe/repos',
      events_url: 'https://api.github.com/users/marotiuppe/events{/privacy}',
      received_events_url: 'https://api.github.com/users/marotiuppe/received_events',
      type: 'User',
      site_admin: false
    },
    html_url: 'https://github.com/marotiuppe/my-portfolio',
    description: 'A dynamic portfolio application built with Angular, showcasing my professional journey and skills. The project features components for About, Experience, Skills, Education, and Projects.',
    fork: false,
    url: 'https://api.github.com/repos/marotiuppe/my-portfolio',
    forks_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/forks',
    keys_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/teams',
    hooks_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/hooks',
    issue_events_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/issues/events{/number}',
    events_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/events',
    assignees_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/assignees{/user}',
    branches_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/branches{/branch}',
    tags_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/tags',
    blobs_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/languages',
    stargazers_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/stargazers',
    contributors_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/contributors',
    subscribers_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/subscribers',
    subscription_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/subscription',
    commits_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/contents/{+path}',
    compare_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/merges',
    archive_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/downloads',
    issues_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/issues{/number}',
    pulls_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/labels{/name}',
    releases_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/releases{/id}',
    deployments_url: 'https://api.github.com/repos/marotiuppe/my-portfolio/deployments',
    created_at: '2024-07-25T16:53:26Z',
    updated_at: '2024-07-27T10:50:33Z',
    pushed_at: '2024-07-27T07:32:24Z',
    git_url: 'git://github.com/marotiuppe/my-portfolio.git',
    ssh_url: 'git@github.com:marotiuppe/my-portfolio.git',
    clone_url: 'https://github.com/marotiuppe/my-portfolio.git',
    svn_url: 'https://github.com/marotiuppe/my-portfolio',
    homepage: 'https://i-am-maroti.netlify.app/',
    size: 9480,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'TypeScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [
      'i-am-maroti',
      'maroti-uppe',
      'portfolio',
      'portfolio-site',
      'portfolio-template',
      'portfolio-website'
    ],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'main',
    languages: {
      HTML: 562171,
      CSS: 489886,
      SCSS: 72316,
      JavaScript: 31607,
      TypeScript: 15517
    }
  },
  {
    id: 771618503,
    node_id: 'R_kgDOLf32xw',
    name: 'qc-control-center-v1',
    full_name: 'marotiuppe/qc-control-center-v1',
    private: false,
    owner: {
      login: 'marotiuppe',
      id: 61408288,
      node_id: 'MDQ6VXNlcjYxNDA4Mjg4',
      avatar_url: 'https://avatars.githubusercontent.com/u/61408288?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/marotiuppe',
      html_url: 'https://github.com/marotiuppe',
      followers_url: 'https://api.github.com/users/marotiuppe/followers',
      following_url: 'https://api.github.com/users/marotiuppe/following{/other_user}',
      gists_url: 'https://api.github.com/users/marotiuppe/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/marotiuppe/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/marotiuppe/subscriptions',
      organizations_url: 'https://api.github.com/users/marotiuppe/orgs',
      repos_url: 'https://api.github.com/users/marotiuppe/repos',
      events_url: 'https://api.github.com/users/marotiuppe/events{/privacy}',
      received_events_url: 'https://api.github.com/users/marotiuppe/received_events',
      type: 'User',
      site_admin: false
    },
    html_url: 'https://github.com/marotiuppe/qc-control-center-v1',
    description: 'A robust application designed to manage and track quality control issues. It provides a comprehensive solution for identifying, monitoring, and resolving QC problems, ensuring efficient management and resolution of quality concerns.',
    fork: false,
    url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1',
    forks_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/forks',
    keys_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/teams',
    hooks_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/hooks',
    issue_events_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/issues/events{/number}',
    events_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/events',
    assignees_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/assignees{/user}',
    branches_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/branches{/branch}',
    tags_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/tags',
    blobs_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/languages',
    stargazers_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/stargazers',
    contributors_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/contributors',
    subscribers_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/subscribers',
    subscription_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/subscription',
    commits_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/contents/{+path}',
    compare_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/merges',
    archive_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/downloads',
    issues_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/issues{/number}',
    pulls_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/labels{/name}',
    releases_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/releases{/id}',
    deployments_url: 'https://api.github.com/repos/marotiuppe/qc-control-center-v1/deployments',
    created_at: '2024-03-13T16:22:57Z',
    updated_at: '2024-07-27T10:56:32Z',
    pushed_at: '2024-03-21T04:57:23Z',
    git_url: 'git://github.com/marotiuppe/qc-control-center-v1.git',
    ssh_url: 'git@github.com:marotiuppe/qc-control-center-v1.git',
    clone_url: 'https://github.com/marotiuppe/qc-control-center-v1.git',
    svn_url: 'https://github.com/marotiuppe/qc-control-center-v1',
    homepage: '',
    size: 157,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'TypeScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: false,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: ['management', 'qc', 'qc-control', 'qc-management'],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'master',
    languages: { TypeScript: 42917, HTML: 23869, CSS: 3346 }
  },
  {
    id: 683656670,
    node_id: 'R_kgDOKL_F3g',
    name: 'Rajkumar_tailors',
    full_name: 'marotiuppe/Rajkumar_tailors',
    private: false,
    owner: {
      login: 'marotiuppe',
      id: 61408288,
      node_id: 'MDQ6VXNlcjYxNDA4Mjg4',
      avatar_url: 'https://avatars.githubusercontent.com/u/61408288?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/marotiuppe',
      html_url: 'https://github.com/marotiuppe',
      followers_url: 'https://api.github.com/users/marotiuppe/followers',
      following_url: 'https://api.github.com/users/marotiuppe/following{/other_user}',
      gists_url: 'https://api.github.com/users/marotiuppe/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/marotiuppe/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/marotiuppe/subscriptions',
      organizations_url: 'https://api.github.com/users/marotiuppe/orgs',
      repos_url: 'https://api.github.com/users/marotiuppe/repos',
      events_url: 'https://api.github.com/users/marotiuppe/events{/privacy}',
      received_events_url: 'https://api.github.com/users/marotiuppe/received_events',
      type: 'User',
      site_admin: false
    },
    html_url: 'https://github.com/marotiuppe/Rajkumar_tailors',
    description: 'Rajkumar Tailors is a sleek, responsive website for a tailor shop, It offers an elegant platform for customers to view services, book appointments, and explore tailoring options.',
    fork: false,
    url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors',
    forks_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/forks',
    keys_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/teams',
    hooks_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/hooks',
    issue_events_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/issues/events{/number}',
    events_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/events',
    assignees_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/assignees{/user}',
    branches_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/branches{/branch}',
    tags_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/tags',
    blobs_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/languages',
    stargazers_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/stargazers',
    contributors_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/contributors',
    subscribers_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/subscribers',
    subscription_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/subscription',
    commits_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/contents/{+path}',
    compare_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/merges',
    archive_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/downloads',
    issues_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/issues{/number}',
    pulls_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/labels{/name}',
    releases_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/releases{/id}',
    deployments_url: 'https://api.github.com/repos/marotiuppe/Rajkumar_tailors/deployments',
    created_at: '2023-08-27T09:31:12Z',
    updated_at: '2024-07-27T10:32:33Z',
    pushed_at: '2023-10-20T05:57:48Z',
    git_url: 'git://github.com/marotiuppe/Rajkumar_tailors.git',
    ssh_url: 'git@github.com:marotiuppe/Rajkumar_tailors.git',
    clone_url: 'https://github.com/marotiuppe/Rajkumar_tailors.git',
    svn_url: 'https://github.com/marotiuppe/Rajkumar_tailors',
    homepage: 'https://rajkumar-tailors.vercel.app',
    size: 30324,
    stargazers_count: 1,
    watchers_count: 1,
    language: 'CSS',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [
      'angular',
      'rajkumar',
      'rajkumar-tailors',
      'rajkumar-tailorsshop',
      'respinsive',
      'tailors',
      'tailorsshop'
    ],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 1,
    default_branch: 'main',
    languages: {
      CSS: 520359,
      Java: 198834,
      JavaScript: 193926,
      SCSS: 72316,
      HTML: 46383,
      TypeScript: 41610
    }
  }
]
